name: Build PDF from Markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Convert Markdown to PDF
        run: |
          mkdir -p output
          for file in $(find docs -name "*.md"); do
            filename=$(basename "$file" .md)
            pandoc "$file" -o "output/$filename.pdf"
          done

      - name: Upload PDFs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-reports
          path: output/*.pdf
